import { useState } from 'react';
import { useGet } from '../lib/api';
import { useAuth } from '../context/Auth';
import { Async, Avatar, Card, Delta, Icon, Kpi, PageHead, Segmented, Tabs } from '../ui';
import { BarChart, Donut, HBars, LineChart } from '../ui/charts';
import { fmt, downloadBlob, METHOD, MC } from '../lib/format';

export default function Analytics() {
  const { clinic, clinicById, types } = useAuth(); const [tab, setTab] = useState('activite'); const [range, setRange] = useState(12);
  const q = useGet('/analytics', { range });
  const exportCsv = d => downloadBlob('﻿mois;chiffre_affaires;consultations;nouveaux_patients;taux_remplissage;no_show\n' + d.history.map(h => [h.m.slice(0, 7), h.revenue, h.consults, h.newPatients, h.fill, h.noshow].join(';')).join('\n'), 'nacre-analytics.csv', 'text/csv');
  return <Async q={q}>{d => { const h = d.history; const L = h.map(x => fmt.mshort(x.m)); const last = h[h.length - 1], prev = h[h.length - 2]; const pct = (a, b) => (a / b - 1) * 100;
    return <>
      <PageHead title="Analytics" sub={`${clinic === 'all' ? 'Vue consolidée — tous les établissements' : (clinicById(clinic) || {}).name} · graphiques interactifs`} actions={<><Segmented value={range} onChange={setRange} options={[[6, '6 mois'], [12, '12 mois']]} /><button className="btn" onClick={() => exportCsv(d)}><Icon name="download" />Exporter CSV</button></>} />
      <div className="mb-16"><Tabs value={tab} onChange={setTab} tabs={[{ key: 'activite', label: 'Activité', icon: 'activity' }, { key: 'finance', label: 'Finance', icon: 'wallet' }, { key: 'patients', label: 'Patients', icon: 'users' }, { key: 'traitements', label: 'Traitements', icon: 'clipboard' }]} /></div>
      {tab === 'activite' && <>
        <div className="grid g4 mb-16"><Kpi label="Consultations (mois)" value={fmt.num(last.consults)} icon="stethoscope" tone="tone-blue" foot={<Delta v={pct(last.consults, prev.consults)} />} /><Kpi label="Nouveaux patients" value={last.newPatients} icon="user" tone="tone-teal" foot={<Delta v={pct(last.newPatients, prev.newPatients)} />} /><Kpi label="Patients récurrents" value={Math.round((last.recurrent / last.consults) * 100) + ' %'} icon="repeat" tone="tone-violet" foot={<span>des consultations</span>} /><Kpi label="Taux de remplissage" value={last.fill + ' %'} icon="target" tone="tone-green" foot={<span>no-show {fmt.pct(last.noshow)}</span>} /></div>
        <div className="grid g2 mb-16"><Card title="Consultations" actions={<div className="legend"><span><i style={{ background: '#2C6BCB' }} />Total</span><span><i style={{ background: '#5E9F8D' }} />Patients récurrents</span></div>}><LineChart labels={L} series={[{ name: 'Consultations', data: h.map(x => x.consults), color: '#2C6BCB' }, { name: 'Récurrents', data: h.map(x => x.recurrent), color: '#5E9F8D' }]} height={230} /></Card>
          <Card title="Nouveaux patients"><BarChart labels={L} series={[{ name: 'Nouveaux patients', data: h.map(x => x.newPatients), color: '#3AA6A0' }]} height={230} /></Card></div>
        <div className="grid g2"><Card title="Taux de remplissage & no-show" actions={<div className="legend"><span><i style={{ background: '#12264A' }} />Remplissage</span><span><i style={{ background: '#CF4759' }} />No-show</span></div>}><LineChart labels={L} series={[{ name: 'Remplissage (%)', data: h.map(x => x.fill), color: '#12264A' }, { name: 'No-show (%)', data: h.map(x => x.noshow), color: '#CF4759', dash: true }]} height={220} fmtV={v => v + ' %'} /></Card>
          <Card title="Affluence par créneau" sub="60 derniers jours · rendez-vous par jour et heure"><Heat d={d.activity} /></Card></div>
      </>}
      {tab === 'finance' && <>
        <div className="grid g4 mb-16"><Kpi label="Chiffre d’affaires (mois)" value={fmt.money(last.revenue)} icon="trend" tone="tone-gold" foot={<Delta v={pct(last.revenue, prev.revenue)} />} /><Kpi label="Panier moyen" value={fmt.money(last.revenue / last.consults)} icon="wallet" tone="tone-blue" foot={<span>par consultation</span>} /><Kpi label="CA cumulé" value={fmt.money(h.reduce((s, x) => s + x.revenue, 0))} icon="bars" tone="tone-navy" foot={<span>{range} mois</span>} /><Kpi label="Impayés" value={fmt.money(d.finance.aging.reduce((a, b) => a + b, 0))} icon="alert" tone="tone-red" foot={<span>dont {fmt.money(d.finance.aging[3])} &gt; 90 j</span>} /></div>
        <Card className="mb-16" title="Chiffre d’affaires mensuel" actions={<div className="legend"><span><i style={{ background: '#2C6BCB' }} />Cette année</span><span><i style={{ background: '#D8DEE6' }} />Année précédente</span></div>}><BarChart labels={L} series={[{ name: 'Année précédente', data: h.map(x => Math.round((x.revenue * 0.87) / 1000) * 1000), color: '#D8DEE6' }, { name: 'Cette année', data: h.map(x => x.revenue), color: '#2C6BCB' }]} height={250} fmtV={fmt.money} /></Card>
        <div className="grid g3"><Card title="Revenus par traitement" actions={<span className="xs muted">60 j</span>}><HBars fmtV={fmt.money} rows={Object.entries(d.finance.revByType).sort((a, b) => b[1] - a[1]).slice(0, 7).map(([k, v]) => ({ label: types[k].label, value: v, color: types[k].color }))} /></Card>
          <Card title="Paiements par mode" actions={<span className="xs muted">60 j</span>}><Donut size={150} fmtV={fmt.money} data={Object.entries(d.finance.byMethod).map(([k, v]) => ({ label: METHOD[k], value: v, color: MC[k] }))} center={fmt.k(Object.values(d.finance.byMethod).reduce((a, b) => a + b, 0))} sub="DH" /></Card>
          <Card title="Ancienneté des impayés"><HBars fmtV={fmt.money} rows={[['0–30 jours', 'var(--sage)'], ['31–60 jours', 'var(--warning)'], ['61–90 jours', '#E0582F'], ['+ de 90 jours', 'var(--danger)']].map(([l, c], i) => ({ label: l, value: d.finance.aging[i], color: c }))} /></Card></div>
      </>}
      {tab === 'patients' && <>
        <div className="grid g4 mb-16"><Kpi label="Patients actifs" value={d.patients.active} icon="users" tone="tone-blue" /><Kpi label="Taux de fidélisation" value={d.patients.retention + ' %'} icon="heart" tone="tone-red" foot={<span>≥ 2 visites</span>} /><Kpi label="Fréquence moyenne" value={fmt.dec(d.patients.frequency) + ' visites'} icon="repeat" tone="tone-violet" foot={<span>par patient (60 j)</span>} /><Kpi label="Réservations en ligne" value={d.patients.online + ' %'} icon="globe" tone="tone-teal" foot={<span>des RDV à venir</span>} /></div>
        <div className="grid g3"><Card title="Acquisition" actions={<span className="xs muted">Source déclarée</span>}><Donut size={150} fmtV={v => v + ' %'} center="100" sub="%" data={[['Bouche-à-oreille', 38, '#12264A'], ['Google / Maps', 24, '#2C6BCB'], ['Réservation en ligne', 18, '#3AA6A0'], ['Réseaux sociaux', 12, '#B89457'], ['Adressé par confrère', 8, '#7568D1']].map(([label, value, color]) => ({ label, value, color }))} /></Card>
          <Card title="Fréquence des visites" actions={<span className="xs muted">60 j</span>}><BarChart labels={Object.keys(d.patients.freq)} series={[{ name: 'Patients', data: Object.values(d.patients.freq), color: '#5E9F8D' }]} height={200} /></Card>
          <Card title="Répartition par âge"><HBars rows={d.patients.ages} /><div className="divider" /><div className="row between small"><span>Femmes <b>{d.patients.women}</b></span><span>Hommes <b>{d.patients.men}</b></span></div></Card></div>
      </>}
      {tab === 'traitements' && <>
        <div className="grid g4 mb-16"><Kpi label="Plans acceptés" value={d.treatments.accepted} icon="check" tone="tone-green" foot={<span>sur {d.treatments.plans} proposés</span>} /><Kpi label="Plans en cours" value={d.treatments.inProgress} icon="activity" tone="tone-blue" /><Kpi label="Plans terminés" value={d.treatments.done} icon="badge" tone="tone-gold" /><Kpi label="Conversion des devis" value={d.treatments.quoteConv + ' %'} icon="trend" tone="tone-violet" /></div>
        <div className="grid g2"><Card title="Traitements les plus réalisés" actions={<span className="xs muted">60 derniers jours</span>}><HBars rows={Object.entries(d.treatments.byType).sort((a, b) => b[1] - a[1]).map(([k, v]) => ({ label: types[k].label, value: v, color: types[k].color }))} /></Card>
          <Card title="Entonnoir des plans de traitement">{[['Proposés', d.treatments.plans, '#9AA5B4'], ['Acceptés', d.treatments.accepted, '#7568D1'], ['Planifiés / en cours', d.treatments.inProgress + d.treatments.done, '#2C6BCB'], ['Terminés', d.treatments.done, '#2E9C6E']].map(([l, v, c], i) => <div key={l} style={{ margin: '0 auto 8px', width: `${100 - i * 14}%`, background: c, color: '#fff', borderRadius: 10, padding: '12px 16px', display: 'flex', justifyContent: 'space-between', fontWeight: 600 }}><span>{l}</span><span>{v}{i > 0 && <span style={{ opacity: 0.75, fontWeight: 500 }}> · {Math.round((v / (d.treatments.plans || 1)) * 100)} %</span>}</span></div>)}<div className="small muted center mt-12">Valeur moyenne d’un plan : <b style={{ color: 'var(--ink)' }}>{fmt.money(d.treatments.planValue)}</b></div></Card></div>
      </>}
      <Card className="mt-16" title="Statistiques par praticien" sub="60 derniers jours" bodyClass="table-wrap"><table className="table"><thead><tr><th>Praticien</th><th className="num">Actes réalisés</th><th className="num">CA produit</th><th className="num">No-show</th><th className="num">Patients</th><th className="num">Satisfaction</th></tr></thead>
        <tbody>{d.dentists.map(x => <tr key={x.id}><td><div className="row"><Avatar p={x} size="sm" /><div><b style={{ fontWeight: 500 }}>{x.name}</b><div className="xs muted">{x.spec}</div></div></div></td><td className="num">{x.done}</td><td className="num">{fmt.money(x.revenue)}</td><td className="num">{fmt.pct(x.noshow)}</td><td className="num">{x.patients}</td><td className="num">★ {fmt.dec(x.rating)}</td></tr>)}</tbody></table></Card>
    </>; }}</Async>;
}

function Heat({ d }) {
  const days = ['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam']; const max = Math.max(1, ...d.heat.flat());
  return <div style={{ overflowX: 'auto' }}><table style={{ borderCollapse: 'separate', borderSpacing: 4, width: '100%', minWidth: 480 }}><thead><tr><th />{d.hours.map(h => <th key={h} className="xs faint" style={{ fontWeight: 500 }}>{h}h</th>)}</tr></thead>
    <tbody>{d.heat.map((row, i) => <tr key={i}><td className="xs muted" style={{ paddingRight: 6 }}>{days[i]}</td>{row.map((v, j) => <td key={j} title={`${days[i]} ${d.hours[j]}h : ${v} RDV`} style={{ height: 28, borderRadius: 6, background: `rgba(44,107,203,${(0.06 + (v / max) * 0.85).toFixed(2)})`, textAlign: 'center', fontSize: 11, color: v / max > 0.55 ? '#fff' : 'var(--ink-2)' }}>{v || ''}</td>)}</tr>)}</tbody></table></div>;
}
